dbfilename redis_queue.rdb
dir /Users/harithoppil/Desktop/game/erp-aries/frappe-bench/config/pids
pidfile /Users/harithoppil/Desktop/game/erp-aries/frappe-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /Users/harithoppil/Desktop/game/erp-aries/frappe-bench/config/redis_queue.acl
